<Project Sdk="Godot.NET.Sdk/4.6.2">
  <PropertyGroup>
    <!-- Build Configuration -->
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>14.0</LangVersion>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Nullable>annotations</Nullable>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <EnforceCodeStyleInBuilds>true</EnforceCodeStyleInBuilds>
    <EnableUnsafeBinaryFormatterSerialization>false</EnableUnsafeBinaryFormatterSerialization>
    <BuildInParallel>true</BuildInParallel>

    <!-- Performance -->
    <TieredCompilation>true</TieredCompilation>
    <Deterministic>true</Deterministic>
    <UseSharedCompilation>true</UseSharedCompilation>
    <Optimize>true</Optimize>
    <SkipLocalsInit>true</SkipLocalsInit>
    <ImplicitUsings>disable</ImplicitUsings>

    <NoWarn>$(NoWarn);CA2213;CA1501;CA1812</NoWarn>
  </PropertyGroup>
  
  <ItemGroup>
    <Compile Remove="Assets/Mods/**" />
    <Compile Remove="TheNomad.Tests/**" />
    <Compile Remove="Source/NomadFramework/**" />
    <Compile Remove="android/build/**/*.cs" />
    <Compile Remove="**/bin/**/*.cs" />
    <Compile Remove="**/obj/**/*.cs" />
  </ItemGroup>
  <ItemGroup>
    <!-- Ensures the source generation works correctly -->
    <ProjectReference Include="Source\NomadFramework\Source\Nomad.Core\Nomad.Core.csproj" />
    <ProjectReference Include="Source\NomadFramework\Source\Nomad.Audio.FMOD\Nomad.Audio.FMOD.csproj" />
    <ProjectReference Include="Source\NomadFramework\Source\Nomad.EngineUtils.Settings\Nomad.EngineUtils.Settings.csproj" />

    <ProjectReference Include="Source\NomadFramework\Source\Nomad.SourceGenerators\Nomad.SourceGenerators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />

    <ProjectReference Include="Source\NomadFramework\Source\Nomad.EngineUtils.Godot\Nomad.EngineUtils.Godot.csproj" />
    <ProjectReference Include="Source\NomadFramework\Source\Nomad.Logger\Nomad.Logger.csproj" />
    <ProjectReference Include="Source\NomadFramework\Source\Nomad.FileSystem\Nomad.FileSystem.csproj" />
    <ProjectReference Include="Source\NomadFramework\Source\Nomad.CVars\Nomad.CVars.csproj" />
    <ProjectReference Include="Source\NomadFramework\Source\Nomad.Events\Nomad.Events.csproj" />
    <ProjectReference Include="Source\NomadFramework\Source\Nomad.Input\Nomad.Input.csproj" />
    <ProjectReference Include="Source\NomadFramework\Source\Nomad.Console\Nomad.Console.csproj" />
    <ProjectReference Include="Source\NomadFramework\Source\Nomad.Save\Nomad.Save.csproj" />
    <ProjectReference Include="Source\NomadFramework\Source\Nomad.ResourceCache\Nomad.ResourceCache.csproj" />
    <ProjectReference Include="Source\NomadFramework\Source\Nomad.OnlineServices.Steam\Nomad.OnlineServices.Steam.csproj" />
    <ProjectReference Include="Source\NomadFramework\Source\Nomad.Networking\Nomad.Networking.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Condition="'$(IsWindows)' == 'true'" Include="steam_api64.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <PackageCopyToOutput>true</PackageCopyToOutput>
    </Content>
    <Content Condition="'$(IsWindows)' == 'true'" Include="steam_api.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <PackageCopyToOutput>true</PackageCopyToOutput>
    </Content>
  </ItemGroup>

  <PropertyGroup>
    <IsWindows Condition="'$([System.Runtime.InteropServices.RuntimeInformation]::IsOSPlatform($([System.Runtime.InteropServices.OSPlatform]::Windows)))' == 'true'">true</IsWindows>
    <IsLinux Condition="'$([System.Runtime.InteropServices.RuntimeInformation]::IsOSPlatform($([System.Runtime.InteropServices.OSPlatform]::Linux)))' == 'true'">true</IsLinux>
  </PropertyGroup>

  <PropertyGroup Condition="'$(IsWindows)' == 'true'">
    <DefineConstants>WINDOWS</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(IsLinux)' == 'true'">
    <DefineConstants>LINUX</DefineConstants>
  </PropertyGroup>

</Project>
