<Project Sdk="Godot.NET.Sdk/4.5.1">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <TargetFramework Condition=" '$(GodotTargetPlatform)' == 'android' ">net9.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Nullable>enable</Nullable>
    <PubishAOT>true</PubishAOT>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <EnforceCodeStyleInBuilds>true</EnforceCodeStyleInBuilds>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Source/NomadBackend/**" />
    <Compile Remove="Source/GUIDE/**" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="Source\NomadBackend\Core\Core.csproj" />
    <ProjectReference Include="Source\NomadBackend\Systems\EventSystem\EventSystem\EventSystem.csproj" />
    <ProjectReference Include="Source\NomadBackend\Systems\Audio\Audio.csproj" />
    <ProjectReference Include="Source\NomadBackend\Systems\SaveSystem\SaveSystem.csproj" />
    <ProjectReference Include="Source\NomadBackend\Systems\ResourceCache\ResourceCache.csproj" />
    <ProjectReference Include="Source\NomadBackend\Systems\ConsoleSystem\ConsoleSystem.csproj" />
  </ItemGroup>
</Project>