<Project Sdk="Godot.NET.Sdk/4.6.1">
  <PropertyGroup>
    <!-- Build Configuration -->
    <TargetFramework>net10.0</TargetFramework>
    <TargetFramework Condition=" '$(GodotTargetPlatform)' == 'android' ">net10.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Nullable>enable</Nullable>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <EnforceCodeStyleInBuilds>true</EnforceCodeStyleInBuilds>
    <EnableUnsafeBinaryFormatterSerialization>false</EnableUnsafeBinaryFormatterSerialization>
    <BuildInParallel>true</BuildInParallel>

    <!-- Performance -->
    <TieredCompilation>true</TieredCompilation>
    <Deterministic>true</Deterministic>
    <UseSharedCompilation>true</UseSharedCompilation>
    <Optimize>true</Optimize>
    <SkipLocalsInit>true</SkipLocalsInit>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Godot.NET.Sdk" Version="4.6.1" />
    <PackageReference Include="Godot.SourceGenerators" Version="4.6.1" />
    <PackageReference Include="GodotSharp" Version="4.6.1" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="Source\NomadFramework\**" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="Source\NomadFramework\Source\Nomad.Core\Nomad.Core.csproj" />
    <ProjectReference Include="Source\NomadFramework\Source\Nomad.Audio.FMOD\Nomad.Audio.FMOD.csproj" />
    <ProjectReference Include="Source\NomadFramework\Source\Nomad.EngineUtils.Settings\Nomad.EngineUtils.Settings.csproj" />
    <ProjectReference Include="Source\NomadFramework\Source\Nomad.EngineUtils.Godot\Nomad.EngineUtils.Godot.csproj" />
    <ProjectReference Include="Source\NomadFramework\Source\Nomad.Logger\Nomad.Logger.csproj" />
    <ProjectReference Include="Source\NomadFramework\Source\Nomad.FileSystem\Nomad.FileSystem.csproj" />
    <ProjectReference Include="Source\NomadFramework\Source\Nomad.CVars\Nomad.CVars.csproj" />
	  <ProjectReference Include="Source\NomadFramework\Source\Nomad.Events\Nomad.Events.csproj" />
    <ProjectReference Include="Source\NomadFramework\Source\Nomad.Console\Nomad.Console.csproj" />
    <ProjectReference Include="Source\NomadFramework\Source\Nomad.ResourceCache\Nomad.ResourceCache.csproj" />
    <ProjectReference Include="Source\NomadFramework\Source\Nomad.OnlineServices.Steam\Nomad.OnlineServices.Steam.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <IsWindows Condition="'$([System.Runtime.InteropServices.RuntimeInformation]::IsOSPlatform($([System.Runtime.InteropServices.OSPlatform]::Windows)))' == 'true'">true</IsWindows>
    <IsLinux Condition="'$([System.Runtime.InteropServices.RuntimeInformation]::IsOSPlatform($([System.Runtime.InteropServices.OSPlatform]::Linux)))' == 'true'">true</IsLinux>
  </PropertyGroup>

  <PropertyGroup Condition="'$(IsWindows)' == 'true'">
    <DefineConstants>WINDOWS</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(IsLinux)' == 'true'">
    <DefineConstants>LINUX</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <Content Condition="'$(IsWindows)' == 'true'" Include="Source/NomadFramework/Source/Nomad.Audio.FMOD/fmod.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Condition="'$(IsWindows)' == 'true'" Include="Source/NomadFramework/Source/Nomad.Audio.FMOD/fmodL.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Condition="'$(IsWindows)' == 'true'" Include="Source/NomadFramework/Source/Nomad.Audio.FMOD/fmodstudio.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Condition="'$(IsWindows)' == 'true'" Include="Source/NomadFramework/Source/Nomad.Audio.FMOD/fmodstudioL.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Condition="'$(IsLinux)' == 'true'" Include="Source/NomadFramework/Source/Nomad.Audio.FMOD/fmod.so">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Condition="'$(IsLinux)' == 'true'" Include="Source/NomadFramework/Source/Nomad.Audio.FMOD/fmodL.so">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Condition="'$(IsLinux)' == 'true'" Include="Source/NomadFramework/Source/Nomad.Audio.FMOD/libfmod.so">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Condition="'$(IsLinux)' == 'true'" Include="Source/NomadFramework/Source/Nomad.Audio.FMOD/libfmodL.so">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Condition="'$(IsLinux)' == 'true'" Include="Source/NomadFramework/Source/Nomad.Audio.FMOD/libfmodstudio.so">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Condition="'$(IsLinux)' == 'true'" Include="Source/NomadFramework/Source/Nomad.Audio.FMOD/libfmodstudioL.so">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Condition="'$(IsLinux)' == 'true'" Include="Source/NomadFramework/Source/Nomad.OnlineServices.Steam/steam_api64.so">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <PackageCopyToOutput>true</PackageCopyToOutput>
    </Content>
    <Content Condition="'$(IsLinux)' == 'true'" Include="Source/NomadFramework/Source/Nomad.OnlineServices.Steam/steam_api.so">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <PackageCopyToOutput>true</PackageCopyToOutput>
    </Content>
    <Content Condition="'$(IsLinux)' == 'true'" Include="Source/NomadFramework/Source/Nomad.OnlineServices.Steam/libsteam_api.so">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <PackageCopyToOutput>true</PackageCopyToOutput>
    </Content>
  </ItemGroup>
</Project>
