// <auto-generated />
// Generated by FmodAudioCatalogGenerator.
// Do not edit by hand.

using System;
using System.Collections.Generic;

namespace Nomad.Game.Sdk;

public enum AudioEventId
{
    None = 0,
    MusicUserInterfaceMainMenuTheme,
    SoundEffectsAmbienceDesertWinds,
    SoundEffectsFoleyPlayerBodyClothRuffle,
    SoundEffectsFoleyPlayerBodyMetalArm,
    SoundEffectsFoleyPlayerSlide,
    SoundEffectsFoleyPlayerWalkGravel,
    SoundEffectsFoleyPlayerWalkSand,
    SoundEffectsFoleyPlayerWalkStone,
    SoundEffectsFoleyPlayerWalkWood,
    SoundEffectsFXPlayerDashActivate,
    SoundEffectsFXPlayerDashBurnout,
    SoundEffectsFXPlayerDashRecharge,
    SoundEffectsFXPlayerSlowMoEnd,
    SoundEffectsFXPlayerSlowMoStart,
    SoundEffectsFXWeaponsAsturionDoubleBarrelReload,
    SoundEffectsFXWeaponsAsturionDoubleBarrelUse,
    SoundEffectsFXWeaponsDesertRifleReload,
    SoundEffectsFXWeaponsDesertRifleUse,
    SoundEffectsFXWeaponsHardBallerReload,
    SoundEffectsFXWeaponsHardBallerUse,
    SoundEffectsFXWeaponsHeavySluggerReload,
    SoundEffectsFXWeaponsHeavySluggerUse,
    UIBeginGame,
    UIButtonFocused,
    UIButtonPressed,
    UIGamePaused,
    UIGameResumed,
}

public enum AudioSnapshotId
{
    None = 0,
    BulletTime,
}

public enum AudioBusId
{
    None = 0,
    Master,
    Music,
    Reverb,
    ReverbOutdoor,
    SoundEffects,
    SoundEffectsAmbience,
    SoundEffectsFoley,
    SoundEffectsFX,
    SoundEffectsUserInterface,
}

public readonly struct AudioEventDefinition {
	public AudioEventId Id { get; }
	public Guid Guid { get; }
	public string Path { get; }
	public AudioEventDefinition( AudioEventId id, Guid guid, string path ) {
		Id = id;
		Guid = guid;
		Path = path;
	}
}

public readonly struct AudioSnapshotDefinition {
	public AudioSnapshotId Id { get; }
	public Guid Guid { get; }
	public string Path { get; }
	public AudioSnapshotDefinition( AudioSnapshotId id, Guid guid, string path ) {
		Id = id;
		Guid = guid;
		Path = path;
	}
}

public readonly struct AudioBusDefinition {
	public AudioBusId Id { get; }
	public Guid Guid { get; }
	public string Path { get; }
	public AudioBusDefinition( AudioBusId id, Guid guid, string path ) {
		Id = id;
		Guid = guid;
		Path = path;
	}
}

public static partial class AudioEventIdConstants
{
    private static readonly IReadOnlyDictionary<AudioEventId, AudioEventDefinition> _events =
        new Dictionary<AudioEventId, AudioEventDefinition>
        {
            [AudioEventId.MusicUserInterfaceMainMenuTheme] = new AudioEventDefinition(AudioEventId.MusicUserInterfaceMainMenuTheme, new Guid("14434654-6dd0-444f-bb95-4d855e541017"), "event:/Music/UserInterface/MainMenuTheme"),
            [AudioEventId.SoundEffectsAmbienceDesertWinds] = new AudioEventDefinition(AudioEventId.SoundEffectsAmbienceDesertWinds, new Guid("9a58edf6-74ca-45aa-b799-71fe95b7d79d"), "event:/SoundEffects/Ambience/DesertWinds"),
            [AudioEventId.SoundEffectsFoleyPlayerBodyClothRuffle] = new AudioEventDefinition(AudioEventId.SoundEffectsFoleyPlayerBodyClothRuffle, new Guid("197eb14e-e0c4-490f-b883-ef008f7baae5"), "event:/SoundEffects/Foley/Player/Body/ClothRuffle"),
            [AudioEventId.SoundEffectsFoleyPlayerBodyMetalArm] = new AudioEventDefinition(AudioEventId.SoundEffectsFoleyPlayerBodyMetalArm, new Guid("8a76a3e9-5658-40a6-8e5a-845864e7e4b5"), "event:/SoundEffects/Foley/Player/Body/MetalArm"),
            [AudioEventId.SoundEffectsFoleyPlayerSlide] = new AudioEventDefinition(AudioEventId.SoundEffectsFoleyPlayerSlide, new Guid("4d76b293-ddd4-4fa8-aa4c-fd2bf34f9678"), "event:/SoundEffects/Foley/Player/Slide"),
            [AudioEventId.SoundEffectsFoleyPlayerWalkGravel] = new AudioEventDefinition(AudioEventId.SoundEffectsFoleyPlayerWalkGravel, new Guid("1218c35a-68d0-4a80-881f-a6a8e3ff4db9"), "event:/SoundEffects/Foley/Player/Walk/Gravel"),
            [AudioEventId.SoundEffectsFoleyPlayerWalkSand] = new AudioEventDefinition(AudioEventId.SoundEffectsFoleyPlayerWalkSand, new Guid("3f88d86f-9ff5-4867-9d89-9dd655744b57"), "event:/SoundEffects/Foley/Player/Walk/Sand"),
            [AudioEventId.SoundEffectsFoleyPlayerWalkStone] = new AudioEventDefinition(AudioEventId.SoundEffectsFoleyPlayerWalkStone, new Guid("3078a25e-a569-413c-8f04-37f6bd5b9b7d"), "event:/SoundEffects/Foley/Player/Walk/Stone"),
            [AudioEventId.SoundEffectsFoleyPlayerWalkWood] = new AudioEventDefinition(AudioEventId.SoundEffectsFoleyPlayerWalkWood, new Guid("dd64a2a3-fc7c-42fe-b7d3-c204cc837dd6"), "event:/SoundEffects/Foley/Player/Walk/Wood"),
            [AudioEventId.SoundEffectsFXPlayerDashActivate] = new AudioEventDefinition(AudioEventId.SoundEffectsFXPlayerDashActivate, new Guid("3efe5c6b-5ada-48d9-81f3-6f8b88066a23"), "event:/SoundEffects/FX/Player/DashActivate"),
            [AudioEventId.SoundEffectsFXPlayerDashBurnout] = new AudioEventDefinition(AudioEventId.SoundEffectsFXPlayerDashBurnout, new Guid("9356ef2b-ac3e-480c-9d4b-2b5dcae56d7b"), "event:/SoundEffects/FX/Player/DashBurnout"),
            [AudioEventId.SoundEffectsFXPlayerDashRecharge] = new AudioEventDefinition(AudioEventId.SoundEffectsFXPlayerDashRecharge, new Guid("893543a9-1238-44ac-b6ac-0c3f9d75029f"), "event:/SoundEffects/FX/Player/DashRecharge"),
            [AudioEventId.SoundEffectsFXPlayerSlowMoEnd] = new AudioEventDefinition(AudioEventId.SoundEffectsFXPlayerSlowMoEnd, new Guid("979c4b7f-9596-409a-a421-a7999e33939d"), "event:/SoundEffects/FX/Player/SlowMoEnd"),
            [AudioEventId.SoundEffectsFXPlayerSlowMoStart] = new AudioEventDefinition(AudioEventId.SoundEffectsFXPlayerSlowMoStart, new Guid("0196dde4-b2b5-434f-b6fe-99df2a17fa17"), "event:/SoundEffects/FX/Player/SlowMoStart"),
            [AudioEventId.SoundEffectsFXWeaponsAsturionDoubleBarrelReload] = new AudioEventDefinition(AudioEventId.SoundEffectsFXWeaponsAsturionDoubleBarrelReload, new Guid("9cedb0ab-5c51-422f-934d-553c0d64a63a"), "event:/SoundEffects/FX/Weapons/AsturionDoubleBarrel/Reload"),
            [AudioEventId.SoundEffectsFXWeaponsAsturionDoubleBarrelUse] = new AudioEventDefinition(AudioEventId.SoundEffectsFXWeaponsAsturionDoubleBarrelUse, new Guid("121ed4df-c05d-4eed-9aa3-02b44c880d06"), "event:/SoundEffects/FX/Weapons/AsturionDoubleBarrel/Use"),
            [AudioEventId.SoundEffectsFXWeaponsDesertRifleReload] = new AudioEventDefinition(AudioEventId.SoundEffectsFXWeaponsDesertRifleReload, new Guid("2860df5c-4f2c-4d93-8793-851fa2b591f1"), "event:/SoundEffects/FX/Weapons/DesertRifle/Reload"),
            [AudioEventId.SoundEffectsFXWeaponsDesertRifleUse] = new AudioEventDefinition(AudioEventId.SoundEffectsFXWeaponsDesertRifleUse, new Guid("96c56580-d3d3-43d8-a1b6-a766fcc5a26c"), "event:/SoundEffects/FX/Weapons/DesertRifle/Use"),
            [AudioEventId.SoundEffectsFXWeaponsHardBallerReload] = new AudioEventDefinition(AudioEventId.SoundEffectsFXWeaponsHardBallerReload, new Guid("a9b430e0-be0e-4420-87a5-88bdcc4d867c"), "event:/SoundEffects/FX/Weapons/HardBaller/Reload"),
            [AudioEventId.SoundEffectsFXWeaponsHardBallerUse] = new AudioEventDefinition(AudioEventId.SoundEffectsFXWeaponsHardBallerUse, new Guid("cd81ff2b-c6ec-4fdb-a7bd-b5ccb3deb781"), "event:/SoundEffects/FX/Weapons/HardBaller/Use"),
            [AudioEventId.SoundEffectsFXWeaponsHeavySluggerReload] = new AudioEventDefinition(AudioEventId.SoundEffectsFXWeaponsHeavySluggerReload, new Guid("8414be19-09d5-4c3a-8c4a-b22fda0d4bb4"), "event:/SoundEffects/FX/Weapons/HeavySlugger/Reload"),
            [AudioEventId.SoundEffectsFXWeaponsHeavySluggerUse] = new AudioEventDefinition(AudioEventId.SoundEffectsFXWeaponsHeavySluggerUse, new Guid("8c48b8d9-e098-4633-8309-e154d727bc28"), "event:/SoundEffects/FX/Weapons/HeavySlugger/Use"),
            [AudioEventId.UIBeginGame] = new AudioEventDefinition(AudioEventId.UIBeginGame, new Guid("5e6a415b-a6e4-43f3-86ae-addaca3f561b"), "event:/UI/BeginGame"),
            [AudioEventId.UIButtonFocused] = new AudioEventDefinition(AudioEventId.UIButtonFocused, new Guid("066eb725-8ee2-4726-86ae-6ef03cde6375"), "event:/UI/ButtonFocused"),
            [AudioEventId.UIButtonPressed] = new AudioEventDefinition(AudioEventId.UIButtonPressed, new Guid("fac83f7b-bd06-4a73-a8ae-678ac7c4a5e7"), "event:/UI/ButtonPressed"),
            [AudioEventId.UIGamePaused] = new AudioEventDefinition(AudioEventId.UIGamePaused, new Guid("eb7d0a04-788e-4e12-87a9-49f54838b4b7"), "event:/UI/GamePaused"),
            [AudioEventId.UIGameResumed] = new AudioEventDefinition(AudioEventId.UIGameResumed, new Guid("67774ba2-46b4-4e39-9cdd-67017fa89fdc"), "event:/UI/GameResumed"),
        };

    private static readonly IReadOnlyDictionary<AudioSnapshotId, AudioSnapshotDefinition> _snapshots =
        new Dictionary<AudioSnapshotId, AudioSnapshotDefinition>
        {
            [AudioSnapshotId.BulletTime] = new AudioSnapshotDefinition(AudioSnapshotId.BulletTime, new Guid("d1056d5f-0ee4-431f-8a5d-9c11b18dea0d"), "snapshot:/BulletTime"),
        };

    private static readonly IReadOnlyDictionary<AudioBusId, AudioBusDefinition> _buses =
        new Dictionary<AudioBusId, AudioBusDefinition>
        {
            [AudioBusId.Master] = new AudioBusDefinition(AudioBusId.Master, new Guid("f74246d7-60c6-495f-ad9c-a099bef14364"), "bus:/"),
            [AudioBusId.Music] = new AudioBusDefinition(AudioBusId.Music, new Guid("211ba141-6f20-4c43-b43e-65cf54ac58a6"), "bus:/Music"),
            [AudioBusId.Reverb] = new AudioBusDefinition(AudioBusId.Reverb, new Guid("e7f3028c-ea4e-48ca-8fbc-01962bcd81e8"), "bus:/Reverb"),
            [AudioBusId.ReverbOutdoor] = new AudioBusDefinition(AudioBusId.ReverbOutdoor, new Guid("1e3540de-4e81-4686-98e7-39ffad7a4d87"), "bus:/Reverb_Outdoor"),
            [AudioBusId.SoundEffects] = new AudioBusDefinition(AudioBusId.SoundEffects, new Guid("1a7b11c7-fb58-4575-b99c-77628efe6f5d"), "bus:/SoundEffects"),
            [AudioBusId.SoundEffectsAmbience] = new AudioBusDefinition(AudioBusId.SoundEffectsAmbience, new Guid("7fe132a6-aef4-41de-8361-2ea5eeb9fbc4"), "bus:/SoundEffects/Ambience"),
            [AudioBusId.SoundEffectsFoley] = new AudioBusDefinition(AudioBusId.SoundEffectsFoley, new Guid("4da15ed0-63ef-42b1-bfdb-d8190d8e912c"), "bus:/SoundEffects/Foley"),
            [AudioBusId.SoundEffectsFX] = new AudioBusDefinition(AudioBusId.SoundEffectsFX, new Guid("7e8fe60e-d500-4654-8e71-e4e890588c88"), "bus:/SoundEffects/FX"),
            [AudioBusId.SoundEffectsUserInterface] = new AudioBusDefinition(AudioBusId.SoundEffectsUserInterface, new Guid("08340847-5532-4b62-aba9-2e3b5c6c6fb2"), "bus:/SoundEffects/UserInterface"),
        };

    public static AudioEventDefinition GetEvent(AudioEventId id)
    {
        if (_events.TryGetValue(id, out var value))
            return value;

        throw new KeyNotFoundException($"No generated FMOD definition exists for AudioEventId.");
    }

    public static bool TryGetEvent(AudioEventId id, out AudioEventDefinition value)
    {
        return _events.TryGetValue(id, out value);
    }

    public static AudioSnapshotDefinition GetSnapshot(AudioSnapshotId id)
    {
        if (_snapshots.TryGetValue(id, out var value))
            return value;

        throw new KeyNotFoundException($"No generated FMOD definition exists for AudioSnapshotId.");
    }

    public static bool TryGetSnapshot(AudioSnapshotId id, out AudioSnapshotDefinition value)
    {
        return _snapshots.TryGetValue(id, out value);
    }

    public static AudioBusDefinition GetBus(AudioBusId id)
    {
        if (_buses.TryGetValue(id, out var value))
            return value;

        throw new KeyNotFoundException($"No generated FMOD definition exists for AudioBusId.");
    }

    public static bool TryGetBus(AudioBusId id, out AudioBusDefinition value)
    {
        return _buses.TryGetValue(id, out value);
    }

}
