<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>14.0</LangVersion>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <AssemblyName>Nomad.Game.Sdk</AssemblyName>
    <RootNamespace>Nomad.Game.Sdk</RootNamespace>
    <Nullable>annotations</Nullable>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <EnforceCodeStyleInBuilds>true</EnforceCodeStyleInBuilds>
    <EnableUnsafeBinaryFormatterSerialization>false</EnableUnsafeBinaryFormatterSerialization>
    <BuildInParallel>true</BuildInParallel>

    <!-- Performance -->
    <TieredCompilation>true</TieredCompilation>
    <Deterministic>true</Deterministic>
    <UseSharedCompilation>true</UseSharedCompilation>
    <Optimize>true</Optimize>
    <ImplicitUsings>disable</ImplicitUsings>
    <Description>Public SDK contracts, authored definitions, IDs, and behavior extension interfaces for The Nomad.</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../Modding/Nomad.Modding.csproj" />

    <ProjectReference Include="..\..\NomadFramework\Source\Nomad.Core\Nomad.Core.csproj" />
    <ProjectReference Include="..\..\NomadFramework\Source\Nomad.SourceGenerators\Nomad.SourceGenerators.csproj"
                      OutputItemType="Analyzer"
                      ReferenceOutputAssembly="false" />
  </ItemGroup>
</Project>
