<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <!-- Build Configuration -->
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>14.0</LangVersion>
    <Nullable>annotations</Nullable>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <EnforceCodeStyleInBuilds>true</EnforceCodeStyleInBuilds>
    <EnableUnsafeBinaryFormatterSerialization>false</EnableUnsafeBinaryFormatterSerialization>
    <BuildInParallel>true</BuildInParallel>

    <!-- Performance -->
    <TieredCompilation>true</TieredCompilation>
    <Deterministic>true</Deterministic>
    <UseSharedCompilation>true</UseSharedCompilation>
    <Optimize>true</Optimize>
    <SkipLocalsInit>true</SkipLocalsInit>
    <ImplicitUsings>disable</ImplicitUsings>
    <OutputPath>../Dll/</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>

    <NoWarn>$(NoWarn);CA2213;CA1501;CA1812;CA1822;CA1506</NoWarn>
  </PropertyGroup>

  <ItemGroup>
	<ProjectReference Include="../../../../Source/Game/Sdk/Nomad.Game.Sdk.csproj" />
  </ItemGroup>
</Project>
